### PR TITLE
move bundle config to JSON format

### LINKED ISSUE #125: list bundle urls in json rather than in code
so we can dynamically add more bundles!
also bundlefly can reference it

### PR DESCRIPTION
**Pull request by askpatrickw**
Fixes #125 

1. This moves the configuration of bundles to a JSON file: `bundle_config.json` which is added to the setup.py data_files. It is assumed to be in `sys.prefix`. 
2. Fixes a test which was verifying the use of the old method, by using a `test_bundle_config.json`
3. Changes `test_bundle_name` to use the `test_bundle_config.json` value
4. Running the tests didn't work with the first way I was including the config file. I change circup to a package layout, installed it as as package and included the config as package data to fix this and the tests.

### CODE REVIEW

**Comment by askpatrickw** [comment]
Looking at the failures... they initially passed on my end. But I can reproduce the failure now.

**Comment by askpatrickw** [comment]
Comment 4 on the description describes how I fixed the tests. Not sure its the _best_ way. But worked.

**Comment by askpatrickw** [comment]
We should rev the major version number if we merge this.  It might be a breaking change for anyone using the circup.py file name directly.

**Review by jepler — APPROVED** [review]
Makes sense but didn't test.

**Comment by jepler** [comment]
As an improvement, consider using https://pypi.org/project/appdirs/ so that you can look for the config json file first in the user's configuration directory and then to the default list shipped in the package.

**Comment by ladyada** [comment]
fyi @tannewt @jwcooper

**Comment by askpatrickw** [comment]
@jepler Good idea... Do you see that overriding the default or supplementing the default?

**Comment by Neradoc** [comment]
My idea for supporting 3rd party bundles was to have new commands (bundle-add, bundle-remove, bundle-info) that manage a separate list, while the default bundles would always remain. But the ability to override the default list, to maybe disable built-in ones, or change the order (to have a 3rd party neopixel implementation override the adafruit one for example) seems a possibly useful idea. Maybe adding also a bundle-reset command to reset the list to the default one.

**Comment by jepler** [comment]
Probably supplementing the regular list.. (figuring it out silent block this PR from being merged)

**Comment by askpatrickw** [comment]
We could merge this as-is and then work out the design for these other ideas in a new issue.
They're much larger than the original ask.

**Comment by askpatrickw** [comment]
I opened an issue on the [3rd Party Bundle Support - 127](https://github.com/adafruit/circup/issues/127). So we can move this PR along.

**Pull request merged**
