### PR TITLE
Install libraries' dependencies

### LINKED ISSUE #50: Install dependencies
When you are installing one package it may also have other dependencies called out, install those as well.

Not sure how this will work yet, but is the next thing that messes me up in my own workflow where I'm having to get one package then another package.

Not included: uninstall dependencies. Pip doesn't even do that yet.

### PR DESCRIPTION
**Pull request by askpatrickw**
- fixes #50
- Alphabetized the imports
- Alphabetize the functions (Sorry, I know this makes the diff big, but it was hard to find stuff)
- New functions: clean_library_name(), get_dependencies(), libraries_from_requirements()
- Refactored: install()

Fixed along the way (my iterative notes)
 - [x] Right now this works, but it makes circup unbearably slow because its getting dependencies (hitting github) for _every_ library in the bundle. I need to move things around to speed this up so I only call get_dependencies() during the actual installation.
     - Cleaned that up, only gets dependencies for libraries being installed.
- [x] Had to add a way to clean up non-standard library names (my choice of words, there probably isn't a standard) and if the name passed in is the pypi name not the cp library name. `clean_library_name()`
  - [x] When a library is missing __repo__ circup warns the maker that its dependencies can not be installed.
- [x] It also fails one of the tests because I'm adding stuff to the metadata.
    Not doing this any longer.
- [x] It is also only going 3 layers of dependency deep. I need to make this N deep... -- yay! I learned about recursion today.
- [x] Does not handle requirements.txt -- install() was refactored to support this in the same way --install <library(s)> works and tested
- [x] Where can I add --verbose output -- No other functions have verbose, only the click methods. Leaving as-is
- [x] DUNDER_ASSIGN_RE method for determining __repo__ in extract_metadata() does not work on multi-line values #70 Fixed by changing the way the regex works and the way the `result` is constructed which appears to be simpler
- [x] Fixed issue where if the library being installed only had 1 dependency in requirements.txt and that dependency was a non_mcu_library (like Blinka) it would not install the main library. Ex" circup install adafruit_requests

Tested Manually and Passed on MacOS Catalina with Python 3.6.12:

- single library (adafruit_pyportal, which has many nested dependencies)
- list of libraries
- --requirements on empty file
- --requirements with one library
- --requirements with several libraries
- --py on all of the above
- invalid library name ex: `circup install adefruit_io`
- ran circup show >> libraries.txt removed extra lines, and circup install -r  libraries.txt
    - Found some more missing __repo__, non-standard names and and NOT_MCU_LIBRARIES libraries.

Not Tested:
- Windows
- Linux
- Any python version other than python 3.6.12 or 3.9.0

Known Issues:
- Pypixelbuf does not have `__repo__` https://github.com/adafruit/Adafruit_CircuitPython_Pypixelbuf/issues/29
- Assumes branch name is "master" for all libraries - Tracked in #71 
- When you're installing several libraries or when there are lots of dependencies it can output redundant info when its skipping blinka libraries.

### CODE REVIEW

**Comment by askpatrickw** [comment]
I hit a bug... 

```
circup install adafruit_requests
Found device at /Volumes/CIRCUITPY, running CircuitPython 6.1.0-rc.1-18-g672d0e27a.
A newer version of CircuitPython (6.2.0-beta.0) is available.
Searching for dependencies for: ['adafruit_requests']
Skipping:
	adafruit-blinka is not for microcontroller installs.
```

It didn't install... no more time to look at it today.

**Comment by makermelissa** [comment]
Ok, I'll wait for you to address it first. Please re-request a review when fixed. Thanks.

**Comment by askpatrickw** [comment]
OK... I think we're good to go. I updated my notes in the main description. Requesting review...

**Comment by makermelissa** [comment]
Thanks, I'll test it out today.

**Review by makermelissa — APPROVED** [review]
Tested on PyPortal with no libraries, which I thought might trip it up, and it worked beautifully.

**Pull request merged**
