### PR TITLE
Add MATCH parameter to the show command to limit the list of modules.

### LINKED ISSUE #58: Add optional search argument to circup show
`circup show lc7` would search the libraries for matches and be the functional equivalent of `circup show |grep lc7` which is not very new programmer friendly.

`circup show` should stay unchanged and list all the libraries in the bundle.

```
circup show lc7
Found device at /Volumes/CIRCUITPY, running CircuitPython 6.1.0-beta.2-151-g737828ccb-dirty.
Usage: circup show [OPTIONS]
Try 'circup show --help' for help.

Error: Got unexpected extra argument (lc7)

code/local/circuit-python-scripts via 🐍 cp_base took 2s
➜ circup show |grep lc7
adafruit_lc709203f
```

This is _very_ helpful when you have a new stemma board in front of you. :-)

### PR DESCRIPTION
**Pull request by cpforbes**
Fixes #58

### CODE REVIEW

**Comment by askpatrickw** [comment]
Hi @cpforbes  Thanks for the PR. 

Question: You added a new command line option match and what was described in the issue was that `cp show` should support an optional argument for filtering the results. Was there a reason you went in this other direction?

**Comment by cpforbes** [comment]
I added a optional match argument (as opposed to option) you can see this in the new help text:
```
$ circup show --help
Found device at /run/media/cpforbes/CIRCUITPY, running CircuitPython 6.1.0-beta.2.
Usage: circup show [OPTIONS] [MATCH]

  Show a list of available modules in the bundle. These are modules which
  *could* be installed on the device.

  If MATCH is specified only matching modules will be listed.

Options:
  --help  Show this message and exit.
```

The new example usage is:
```
$ circup show lc7
Found device at /run/media/cpforbes/CIRCUITPY, running CircuitPython 6.1.0-beta.2.
adafruit_lc709203f
1 shown of 256 packages.
```

**Comment by askpatrickw** [comment]
I'm sorry, I misunderstood the click decorators. Thanks for re-explaining. 

I tested this and it works great!

**Review by askpatrickw — APPROVED** [review]
Reviewed, discussed and tested.

**Pull request merged**
