### PR TITLE
added travis config, linted, fixed up docs

### PR DESCRIPTION
**Pull request by siddacious**
This PR adds PyPi credentials and travis config. Had to add a bunch of pylint disables, made minor tweaks where suggested by pylint.

### CODE REVIEW

**Comment by makermelissa** [comment]
I don't think Blinka is actually required for this one.

**Comment by siddacious** [comment]
> I don't think Blinka is actually required for this one.

ya, you're right.

**Comment by ntoll** [comment]
@siddacious great stuff and thank you for contributing..! :+1:

I have a question: did you look at the docs/Makefile..? There's already a whole bunch of checking and testing going on in there (hint: `make check` will run everything, all the docs are here: https://circup.readthedocs.io/en/latest/).

I'd like to make sure the Makefile is aligned with Adafruit's expectations/conventions and then, perhaps the `travis.yml` script can just run `make check`..? The advantage of this approach is that the developer can run exactly the same test suite in their local dev environment as on Travis before pushing to GitHub.

Totally happy to be guided by you in what the tests are (but like I said, there's already a lot going on in the Makefile which works on Linux, OSX and [via a funky Python script] on Windows too).

**Comment by siddacious** [comment]
@ntoll I only quickly looked at the makefiles, I kinda just threw this together in a hope that it would just work, but I'll take a deeper look today.

I

**Comment by siddacious** [comment]
@ntoll I took a look and like your approach over our standard practice; the black, pyflakes, pep8, and unit test integrations are muy bueno.

I'm going to close this and open a new PR that makes use of your Makefile

**Comment by ntoll** [comment]
@siddacious care to link to the PR? Happy to help if you've questions, comments, concerns etc... Please don't hesitate to get in touch. :-)

**Pull request closed without merging**
