### PR TITLE
Remove 5.x Bundle

### LINKED ISSUE #75: "There was a problem downloading the bundle. Please try again in a moment."
People reported Circup not working today... 
This is probably from the 5.x Bundle being removed.

### PR DESCRIPTION
**Pull request by askpatrickw**
Fixes #75 

- Remove 5.x bundle 
- Test for 2 not 3 bundles

### CODE REVIEW

**Comment by ghayne** [comment]
Didn't work for me!

**Comment by askpatrickw** [comment]
@ghayne  hmm... I'm puzzled. Just to double check, how did you update you local copy of circup to the one in this PR?

**Comment by ghayne** [comment]
> @ghayne hmm... I'm puzzled. Just to double check, how did you update you local copy of circup to the one in this PR?

It did work, apologies for my brain fog!

**Comment by askpatrickw** [comment]
Woo hoo!
Thanks @ghayne !

NOTE: I'm going to approve and push this live because it is breaking for folks (this is the second person I've seen mention it today.)

**Pull request merged**
