### PR TITLE
Fix finding requirements in the community bundle

### PR DESCRIPTION
**Pull request by Neradoc**
The `requirements.txt` files were looked for in a hard-coded `adafruit-circuitpython-bundle-py-*` sub directory, whatever the bundle was, which would fail for the community bundle. This fixes it (and moves the function into the Bundle class). Until we switch to the json file.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Looks good to me! I didn't test.

**Comment by askpatrickw** [comment]
@Neradoc how would I test this? Is there a specific community library which will fail and then work with this PR?

**Comment by Neradoc** [comment]
Oh I forgot to put it in the PR description: `circuitpython_schedule` from the community bundle is the one I tested with, it requires `adafruit_datetime` which is not installed with current, but is with the fix.

**Review by askpatrickw — APPROVED** [review]
Tested
Thank you!

**Pull request merged**
