### PR TITLE
Install

### PR DESCRIPTION
**Pull request by ntoll**
Some bonus features I added when I did the initial block of work.

* show   -  Show a list of available modules in the bundle.
* install - Install a named module onto the device.

Happy to change anything. No problem if this is deemed feature-creep.

### CODE REVIEW

**Comment by ladyada** [comment]
hi thanks - will have @makermelissa take a look when she's done with current task :)

**Comment by makermelissa** [comment]
Ok, there's three things I noticed right away.
1. The show list is comma separated and a bit difficult to read.
2. install didn't appear to work for me. Only after looking and seeing the file there was I able to tell successfully. This is what I got:
```
$ circup install neopixel
Found device at /Volumes/CIRCUITPY, running CircuitPython 5.0.0-alpha.4.
OK
```
3. It would be awesome if there was a way to install the .mpy version vs the .py version of files with an option. If there is, it's not obvious. :)

**Comment by ntoll** [comment]
@makermelissa :+1:  I'll try to fix this up over the weekend.

**Comment by makermelissa** [comment]
Sounds good. Thanks for all your work on this.

**Comment by ntoll** [comment]
@makermelissa OK... I've had a quick look to fix things up. Care to take it for a test drive and let me know how you get on. Happy to make changes. :+1:

**Pull request merged**
