### PR TITLE
add module names completion for install

### PR DESCRIPTION
**Pull request by Neradoc**
This PR adds module names completion for the install command using [click's completion feature](https://click.palletsprojects.com/en/7.x/bashcomplete/).
I installed the completion using the "Activation Script" method, and it works quite well, if a little slowly.

`circup install n`+tab -> `circup install neopixel` (+tab: offers `neopixel` and `neopixel_spi` completions)
`circup install a` + tab -> `circup install adafruit_` + m a g + tab -> `circup install adafruit_magtag `

### CODE REVIEW

**Comment by askpatrickw** [comment]
This sounds so cool! testing it now !

**Comment by askpatrickw** [comment]
I couldn't get it to work... It is only showing me the local files when I tab.

This is the eval and output I used on ZShell


```
eval "(_CIRCUP_COMPLETE=source_zsh circup)"
#compdef circup

_circup_completion() {
    local -a completions
    local -a completions_with_descriptions
    local -a response
    (( ! $+commands[circup] )) && return 1

    response=("${(@f)$( env COMP_WORDS="${words[*]}" \
                        COMP_CWORD=$((CURRENT-1)) \
                        _CIRCUP_COMPLETE="complete_zsh" \
                        circup )}")

    for key descr in ${(kv)response}; do
      if [[ "$descr" == "_" ]]; then
          completions+=("$key")
      else
          completions_with_descriptions+=("$key":"$descr")
      fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi

    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
    compstate[insert]="automenu"
}
```

**Comment by Neradoc** [comment]
I'm using bash, zsh on macOS gave me `zsh: command not found: compdef` error when typing:
`eval "$(_FOO_BAR_COMPLETE=source_zsh foo-bar)"`

Running `autoload -Uz compinit && compinit ` made it work.
https://scriptingosx.com/2019/07/moving-to-zsh-part-5-completions/

**Comment by askpatrickw** [comment]
🤦‍♂️ I left the "$" off the eval command.

`eval "$(_CIRCUP_COMPLETE=source_zsh circup)"` worked. 

Worked great !

**Comment by askpatrickw** [comment]
Should some how-to go in the README or add it to the setup.py?

https://click.palletsprojects.com/en/7.x/setuptools/#setuptools-integration

**Comment by askpatrickw** [comment]
@Neradoc  Any thoughts on adding this to the setup.py? Do you think its a good idea?
I can do that and the README if you're too busy.

**Comment by Neradoc** [comment]
I don't know how to do that, when I looked it up there was mentions that it should not be done from pip but using an installer like apt, which is not an option I think, but I don't know. Typer goes one step beyond what click does, by having a --install-completion option that will install to standard places for your shell, though it didn't quite know how to do that on my mac (which runs .bash_profile and not .bashrc on login shells, but typer put it in bashrc).

**Comment by askpatrickw** [comment]
Finally some quiet time to look at this again ... and yeah, you don't add it to setup.py. You must activate it. 

I think something roughly exactly like this should go in the read me. I'll re-read it later. 

## Library Name Autocomplete

When enabled, circup will autocomplete library names, simliar to other command line tools.

For example:
`circup install n`+tab -> `circup install neopixel` (+tab: offers `neopixel` and `neopixel_spi` completions)
`circup install a` + tab -> `circup install adafruit_` + m a g + tab -> `circup install adafruit_magtag `


## How to Activate Library Name Autocomplete
In order to activate shell completion, you need to inform your shell that completion is available for your script. Any Click application automatically provides support for that. 

For Bash, add this to ~/.bashrc:
`eval "$(_CIRCUP_COMPLETE=source_bash circup)"`

For Zsh, add this to ~/.zshrc:
`eval "$(_CIRCUP_COMPLETE=source_zsh circup)"`

For Fish, add this to ~/.config/fish/completions/foo-bar.fish:
`eval (env _CIRCUP_COMPLETE=source_fish circup)`

Open a new shell to enable completion. Or run the eval command directly in your current shell to enable it temporarily.

### Activation Script

The above eval examples will invoke your application every time a shell is started. This may slow down shell startup time significantly.

Alternatively, export the generated completion code as a static script to be executed. You can ship this file with your builds; tools like Git do this. At least Zsh will also cache the results of completion files, but not eval scripts.

For Bash:
`_CIRCUP_COMPLETE=source_bash circup > circup-complete.sh`

For Zsh:
`_CIRCUP_COMPLETE=source_zsh circup > circup-complete.sh`

For Fish:
`_CIRCUP_COMPLETE=source_zsh circup > circup-complete.sh`

In .bashrc or .zshrc, source the script instead of the eval command:

`. /path/to/circup-complete.sh`

For Fish, add the file to the completions directory:
`_CIRCUP_COMPLETE=source_fish circup > ~/.config/fish/completions/circup-complete.fish`

**Comment by lesamouraipourpre** [comment]
FYI:
Click has just released v8 and has redesigned the auto-complete system:
Ref: https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0
_Some selected changes_
* Redesign the shell completion system. #1484, #1622
  * Support Bash >= 4.4, Zsh, and Fish, with the ability for extensions to add support for other shells.
  * Allow commands, groups, parameters, and types to override their completions suggestions.
  * Groups complete the names commands were registered with, which can differ from the name they were created with.
  * The autocompletion parameter for options and arguments is renamed to shell_complete. The function must take ctx, param, incomplete, must do matching rather than return all values, and must return a list of strings or a list of ShellComplete. The old name and behavior is deprecated and will be removed in 8.1.
  * The env var values used to start completion have changed order. The shell now comes first, such as {shell}\_source rather than source\_{shell}, and is always required.
* Completion correctly parses command line strings with incomplete quoting or escape sequences. #1708
* Extra context settings (obj=..., etc.) are passed on to the completion system. #942
* Include --help option in completion. #1504
* For shell completion, an argument is considered incomplete if its value did not come from the command line args. #1649
* Respect case_sensitive=False when doing shell completion for Choice #1692

Shell Completion docs: https://click.palletsprojects.com/en/8.0.x/shell-completion/

**Comment by lesamouraipourpre** [comment]
I've tested this with Click version 8 on bash and with the following changes

~~`eval "$(_CIRCUP_COMPLETE=source_bash circup)"`~~
`eval "$(_CIRCUP_COMPLETE=bash_source circup)"`

This works the same as the instructions above for Click 7.

There are two issues which will affect either version:
* The suggestions aren't sorted but this is easy to fix.
* The first run of the day is very slow and appears to lock up. This is because it triggers the downloads from github and the visual indicators of these are hidden. I'm not sure what the best way to fix this would be. Some possibilities:
  * Add a do_not_download parameter to `get_bundle_version()`. This will use a previous list if `circup` has been run before.
  * Similiar to above but trigger a download on another thread or in another process.
  * Breaking Change! Split the `update` option into `update` and `upgrade` similar to `apt` on Linux. This would only trigger a download if run with `update` and could print a warning about out-of-date information if it hadn't been run today.
  * Other ??

**Comment by Neradoc** [comment]
The suggestions are sorted now.
Instructions added to the readme.

But it's all for click 7, should I update to click 8 ? They are not compatible, so the `requirements.txt` should be updated anyway to either pin 7.1.2 or demand 8 or above.

**Comment by lesamouraipourpre** [comment]
> The suggestions are sorted now.
> Instructions added to the readme.
> 
> But it's all for click 7, should I update to click 8 ? They are not compatible, so the `requirements.txt` should be updated anyway to either pin 7 or demand 8 or above.

As it's a new feature requiring the user to do some installation to bash shell etc. and the upgrade to click 8 breaks this requiring reinstallation I lean to upgrading to click 8 now.

It comes down to will it break anything else? When I tested implemented for click 8, it was in a clean virtual environment and had no issues. But I segregate what I'm doing into multiple separate virtual environments. Do all users?

When I was testing the multiple bundles PR #110 I ended up with click 8 installed, so I can easily see users having it in their environments.:
```
pip list | grep -i click
click                         8.0.1 
```

**Comment by askpatrickw** [comment]
I updated click to =>8.* in requirements.txt and all the circup tests still passed.
I vote go for it !

**Comment by askpatrickw** [comment]
@Neradoc  does the setup.py also need the Click version updated? When I ran pip install . on a clean virtualenv, it installed 8 from cache, but it was matching click>7.0

```
pip install .
Processing /Users/patrickwalters/code/me/circup
Collecting semver~=2.13
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting Click>=7.0
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting appdirs>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting requests>=2.22.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
     |████████████████████████████████| 145 kB 6.1 MB/s
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Using legacy 'setup.py install' for circup, since package 'wheel' is not installed.
Installing collected packages: semver, Click, appdirs, urllib3, chardet, certifi, idna,  
requests, circup
    Running setup.py install for circup ... done
Successfully installed Click-8.0.1 appdirs-1.4.4 certifi-2021.5.30 chardet-4.0.0  
circup-0.9.6.dev7+gb82b7ac idna-2.10 requests-2.25.1 semver-2.13.0 urllib3-1.26.5
```

setup.py

```
install_requires = [
    "semver~=2.13",
    "Click>=7.0",
    "appdirs>=1.4.3",
    "requests>=2.22.0",
]
```

**Comment by Neradoc** [comment]
Oh I missed that ! I'm not very familiar with pypi.
That can be an issue if somebody has a 7.x in cache yes, updated.

**Review by askpatrickw — APPROVED** [review]
I tested this with the eval and it worked in zsh

**Comment by askpatrickw** [comment]
@Neradoc This now has merge conflicts, can you resolve them?

**Comment by Neradoc** [comment]
Rebased, added a parameter to `ensure_latest_bundle` for the shell completion function, so that it does not attempt to update the bundles if there is a version that is already locally cached (i.e. the `bunble_name-py` directory exists). Any other call still looks up the update as expected.

**Review by askpatrickw — APPROVED** [review]
Tested on ZSH

**Pull request merged**
