### PR TITLE
String Errors

### PR DESCRIPTION
**Pull request by askpatrickw**
It's probably 1000% easier for you just to look at code. 
There's discussion about this in #39

### CODE REVIEW

**Comment by askpatrickw** [comment]
OK, spent way too much time on this, but in the end EVERY example of logging looks like:

`logger.info("This needs to be logged: %s", this_thing)`

I believe the Pylint is being raised erroneously and has regressed from a previously fixed bug
https://github.com/PyCQA/pylint/issues/3362 so I disabled it.

**Comment by askpatrickw** [comment]
Issue for pylint https://github.com/PyCQA/pylint/issues/3362

**Comment by askpatrickw** [comment]
The only way pylint run cleans is with logging-style old.

logger.info('This is percent %s', name) # Old Style, this works and pylints clean
logger.info('This is format and curly: {}'.format(name)) # New Style, this works, gives a pylint error to use lazy %

# This does not work on Python 3.6.12 or 3.9.
# logger.info('This is curly {}', name)

Anyway, last attempt on this. let me know if you prefer something else.

**Comment by ntoll** [comment]
Quick question... why not just log with `f`-strings..? (I believe it will work with Python 3.6+)

**Comment by askpatrickw** [comment]
@ntoll that's what I thought too, but pylint calls that out as a bad coding practice. The reason I learned is that in logging statements which may not get called you only want to do the formatting IF they are are called,  but F-strings are always evaluated even if logging statement they are used in are not called so not using f-strings for this is a performance optimization. For Circup it is probably not a big deal, but it makes pylint happy.

I think I'm explaining that correctly... pls correct me if not.

**Comment by ntoll** [comment]
@askpatrickw aha... that makes sense (as in your explanation, although it doesn't make sense that F-strings are still evaluated even when they're not needed). Oh well, and thanks for explaining this.

**Review by ntoll — APPROVED** [review]
Thanks for the contribution..! :shipit: :+1:

**Comment by siddacious** [comment]
FYI:We're totally ok with disabling a pylint warning if the offending lines make sense in context.

**Comment by askpatrickw** [comment]
@ntoll This is a better explanation than mine: https://github.com/PyCQA/pylint/issues/2354#issuecomment-414481212
@siddacious changing the logging-format-style <air-quote>fixed<air-quote> it

**Pull request merged**
