### PR TITLE
Implement `circup install --auto`

### PR DESCRIPTION
**Pull request by jepler**
`--auto` uses the `findimports` module to determine what is used by code.py (or the filename given by --auto-file=, such as --auto-file=boot.py)

`requirements.txt` is regenerated and its license information has been detached so that it can later be updated more easily with `pip freeze`.

### CODE REVIEW

**Review by FoamyGuy — COMMENTED** [review]
I noticed that it doesn't seem to pick up on `from something import Thing` syntax. Specifically I tested with: https://github.com/adafruit/Adafruit_CircuitPython_Display_Button/blob/main/examples/display_button_simpletest.py

Which imports Button that needs display_text, and display_shapes

If I change the syntax in the example script to `import adafruit_button` and add that as a prefix whenever Button is used then it does find all of the necessary imports and install them.

Perhaps this is an issue with `findimports` more generally. If so there may not be anything to do in circup to help it.

Love this functionality either way. Thanks for working on this @jepler

**Comment by Neradoc** [comment]
Likewise it doesn't work with `import adafruit_esp32spi.adafruit_esp32spi_socket as socket`.
However looking at the return from findimports it returns:
```py
['board', 'os', 'time', 'neopixel', 'adafruit_binascii', 'adafruit_requests', 'adafruit_magtag.Magtag', 'adafruit_esp32spi.adafruit_esp32spi_socket']
```
So if we cut before the `.` that should solve it.
And `circup` has a unit test suite, would it be worth having a unit test for `libraries_from_imports` ?

**Comment by jepler** [comment]
I believe I fixed the cases that you discovered, and added a test.

**Comment by Neradoc** [comment]
Passes all my tests.
Thanks, great feature  👍

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. re-tested with the Button example and it does find all the requirements now.

**Pull request merged**
